"""
AWS Credentials Manager — STS AssumeRole (no stored static keys)
================================================================
Pattern: The user provides a Role ARN they create in their own AWS account,
with a trust policy pointing at this backend. At apply/plan time we call
sts:AssumeRole and get short-lived temporary credentials (~1 hour), injected
ONLY into the specific subprocess's environment — never into LangGraph state,
logs, or disk.

This is the same pattern used by Datadog, Vercel, Snowflake, and other SaaS
platforms that integrate with customer AWS accounts.

Setup for the user:
1. In their AWS account, create an IAM role with:
   - Trust policy: allow sts:AssumeRole from this backend's IAM principal
     (for local dev: the developer's own AWS identity or an EC2 instance role)
   - Permission policy: scoped to only what Terraform needs (read below for
     a minimal policy)
   - ExternalId condition: the value generated by get_or_create_external_id()

2. Copy the Role ARN into the settings page or ROLE_ARN in .env
"""
import os
import re
import uuid
import boto3
from botocore.exceptions import ClientError, NoCredentialsError
from pathlib import Path
from dotenv import load_dotenv, set_key

load_dotenv()

_ENV_FILE = Path(__file__).parent.parent / ".env"

# ── ARN Validation ────────────────────────────────────────────────────────────

_ARN_RE = re.compile(
    r"^arn:aws:iam::\d{12}:role/[\w+=,.@/-]{1,512}$"
)

def validate_role_arn(arn: str) -> bool:
    """Return True if the string is a syntactically valid IAM Role ARN."""
    return bool(_ARN_RE.match(arn.strip()))


# ── External ID (confused-deputy protection) ──────────────────────────────────

def get_or_create_external_id() -> str:
    """
    Return the External ID stored in .env, creating one if absent.
    The External ID is a random UUID generated once and stored permanently.
    It must be included in the role's trust policy condition.
    """
    external_id = os.getenv("AWS_EXTERNAL_ID", "")
    if not external_id:
        external_id = str(uuid.uuid4())
        set_key(str(_ENV_FILE), "AWS_EXTERNAL_ID", external_id)
        os.environ["AWS_EXTERNAL_ID"] = external_id
    return external_id


# ── Credential persistence in .env (ARN only, never a secret) ────────────────

def save_role_arn(role_arn: str):
    """Persist the Role ARN in .env. The ARN is not a secret."""
    set_key(str(_ENV_FILE), "AWS_ROLE_ARN", role_arn.strip())
    os.environ["AWS_ROLE_ARN"] = role_arn.strip()


def get_role_arn() -> str | None:
    """Return the configured Role ARN, or None if not set."""
    return os.getenv("AWS_ROLE_ARN") or None


def get_credentials_status() -> dict:
    """Return a safe status dict for the settings API (never exposes secrets)."""
    role_arn = get_role_arn()
    external_id = get_or_create_external_id()
    return {
        "configured": bool(role_arn),
        "role_arn_masked": _mask_arn(role_arn) if role_arn else None,
        "external_id": external_id,   # not a secret — safe to display
    }


def _mask_arn(arn: str) -> str:
    """Return arn:aws:iam::123456789012:role/****-role-name with account masked."""
    parts = arn.split(":")
    if len(parts) >= 5:
        parts[4] = "************"
    return ":".join(parts)


# ── AssumeRole ────────────────────────────────────────────────────────────────

def assume_role(
    role_arn: str | None = None,
    external_id: str | None = None,
    session_name: str = "terraform-agent-session",
    duration_seconds: int = 3600,
) -> dict:
    """
    Call sts:AssumeRole and return a dict of temporary credential env vars.

    Returns:
        {
            "AWS_ACCESS_KEY_ID":     "...",
            "AWS_SECRET_ACCESS_KEY": "...",
            "AWS_SESSION_TOKEN":     "...",
        }

    Raises:
        ValueError: if Role ARN is not configured or invalid.
        RuntimeError: if AssumeRole call fails (wrong trust policy, etc.)
    """
    if os.getenv("MOCK_AWS") == "true":
        return {
            "AWS_ACCESS_KEY_ID": "mock-access-key",
            "AWS_SECRET_ACCESS_KEY": "mock-secret-key",
            "AWS_SESSION_TOKEN": "mock-session-token",
            "_expires_at": "2099-12-31T23:59:59Z",
        }

    role_arn     = role_arn     or get_role_arn()
    external_id  = external_id  or get_or_create_external_id()

    if not role_arn:
        raise ValueError(
            "AWS Role ARN is not configured. "
            "Go to Settings and paste your IAM Role ARN."
        )
    if not validate_role_arn(role_arn):
        raise ValueError(f"Invalid Role ARN format: {role_arn!r}")

    try:
        sts = boto3.client("sts")
        response = sts.assume_role(
            RoleArn=role_arn,
            RoleSessionName=session_name,
            ExternalId=external_id,
            DurationSeconds=duration_seconds,
        )
    except NoCredentialsError:
        raise RuntimeError(
            "No base AWS credentials found for the backend to call sts:AssumeRole. "
            "Configure the backend host's own AWS identity (IAM role, instance profile, "
            "or environment variables for local dev)."
        )
    except ClientError as e:
        code = e.response["Error"]["Code"]
        msg  = e.response["Error"]["Message"]
        raise RuntimeError(f"sts:AssumeRole failed ({code}): {msg}")

    creds = response["Credentials"]
    return {
        "AWS_ACCESS_KEY_ID":     creds["AccessKeyId"],
        "AWS_SECRET_ACCESS_KEY": creds["SecretAccessKey"],
        "AWS_SESSION_TOKEN":     creds["SessionToken"],
        # Expiry metadata — not injected into subprocess env, just for logging
        "_expires_at": creds["Expiration"].isoformat(),
    }


def test_assume_role() -> dict:
    """
    Assume the configured role and call GetCallerIdentity to validate.
    Used by the settings page "Test Connection" button.

    Returns:
        {"ok": True, "account": "...", "arn": "...", "user_id": "..."}
    or raises RuntimeError with a human-readable message.
    """
    if os.getenv("MOCK_AWS") == "true":
        return {
            "ok": True,
            "account": "123456789012",
            "arn": "arn:aws:iam::123456789012:role/MockTerraForgeRole",
            "user_id": "MOCK-USER-ID",
            "expires_at": "2099-12-31T23:59:59Z",
        }

    cred_env = assume_role()
    env = {k: v for k, v in cred_env.items() if not k.startswith("_")}

    # Call GetCallerIdentity with the temporary creds
    sts = boto3.client(
        "sts",
        aws_access_key_id=env["AWS_ACCESS_KEY_ID"],
        aws_secret_access_key=env["AWS_SECRET_ACCESS_KEY"],
        aws_session_token=env["AWS_SESSION_TOKEN"],
    )
    identity = sts.get_caller_identity()
    return {
        "ok":      True,
        "account": identity["Account"],
        "arn":     identity["Arn"],
        "user_id": identity["UserId"],
        "expires_at": cred_env["_expires_at"],
    }
